name: Build - Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-ts:latest
          target: prod
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop express-ts-demo || true
            docker rm express-ts-demo || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/express-ts:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/express-ts:latest
            docker run -d --name express-ts-demo \
              -p 3000:3000 \
              -e NODE_ENV="production" \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e ACESS_TOKEN_EXPIRATION=3600 \
              -e REFRESH_TOKEN_EXPIRATION=86400 \
              -e VIRTUAL_HOST="duongvm.site" \
              -e VIRTUAL_PORT=3000 \
              -e LETSENCRYPT_HOST="duongvm.site" \
              -e LETSENCRYPT_EMAIL="duongvm57@gmail.com" \
              ${{ secrets.DOCKERHUB_USERNAME }}/express-ts:latest
